
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:myyaowrealtorfltheme/publics/property/main.dart';
import 'package:searchable_listview/searchable_listview.dart';

class OtherSearch extends StatefulWidget {
  const OtherSearch({Key key}) : super(key: key);

  @override
  State<OtherSearch> createState() => _OtherSearchState();
}

class _OtherSearchState extends State<OtherSearch> {
  List<String> citylist=["Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Gujranwala",
    "Peshawar",
    "Multan",
    "Saidu Sharif",
    "Hyderabad City",
    "Islamabad",
    "Quetta",
    "Bahawalpur",
    "Sargodha",
    "Sialkot City",
    "Sukkur",
    "Larkana",
    "Chiniot",
    "Shekhupura",
    "Jhang City",
    "Dera Ghazi Khan",
    "Gujrat",
    "Rahimyar Khan",
    "Kasur",
    "Mardan",
    "Mingaora",
    "Nawabshah",
    "Sahiwal",
    "Mirpur Khas",
    "Okara",
    "Mandi Burewala",
    "Jacobabad",
    "Saddiqabad",
    "Kohat",
    "Muridke",
    "Muzaffargarh",
    "Khanpur",
    "Gojra",
    "Mandi Bahauddin",
    "Abbottabad",
    "Turbat",
    "Dadu",
    "Bahawalnagar",
    "Khuzdar",
    "Pakpattan",
    "Tando Allahyar",
    "Ahmadpur East",
    "Vihari",
    "Jaranwala",
    "New Mirpur",
    "Kamalia",
    "Kot Addu",
    "Nowshera",
    "Swabi",
    "Khushab",
    "Dera Ismail Khan",
    "Chaman",
    "Charsadda",
    "Kandhkot",
    "Chishtian",
    "Hasilpur",
    "Attock Khurd",
    "Muzaffarabad",
    "Mianwali",
    "Jalalpur Jattan",
    "Bhakkar",
    "Zhob",
    "Dipalpur",
    "Kharian",
    "Mian Channun",
    "Bhalwal",
    "Jamshoro",
    "Pattoki",
    "Harunabad",
    "Kahror Pakka",
    "Toba Tek Singh",
    "Samundri",
    "Shakargarh",
    "Sambrial",
    "Shujaabad",
    "Hujra Shah Muqim",
    "Kabirwala",
    "Mansehra",
    "Lala Musa",
    "Chunian",
    "Nankana Sahib",
    "Bannu",
    "Pasrur",
    "Timargara",
    "Parachinar",
    "Chenab Nagar",
    "Gwadar",
    "Abdul Hakim",
    "Hassan Abdal",
    "Tank",
    "Hangu",
    "Risalpur Cantonment",
    "Karak",
    "Kundian",
    "Umarkot",
    "Chitral",
    "Dainyor",
    "Kulachi",
    "Kalat",
    "Kotli",
    "Gilgit",
    "Narowal",
    "Khairpur Mir’s",
    "Khanewal",
    "Jhelum",
    "Haripur",
    "Shikarpur",
    "Rawala Kot",
    "Hafizabad",
    "Lodhran",
    "Malakand",
    "Attock City",
    "Batgram",
    "Matiari",
    "Ghotki",
    "Naushahro Firoz",
    "Alpurai",
    "Bagh",
    "Daggar",
    "Layyah",
    "Tando Muhammad Khan",
    "Chakwal",
    "Badin",
    "Lakki",
    "Rajanpur",
    "Dera Allahyar",
    "Shahdad Kot",
    "Pishin",
    "Sanghar",
    "Upper Dir",
    "Thatta",
    "Dera Murad Jamali",
    "Kohlu",
    "Mastung",
    "Dasu",
    "Athmuqam",
    "Loralai",
    "Barkhan",
    "Musa Khel Bazar",
    "Ziarat",
    "Gandava",
    "Sibi",
    "Dera Bugti",
    "Eidgah",
    "Uthal",
    "Khuzdar",
    "Chilas",
    "Panjgur",
    "Gakuch",
    "Qila Saifullah",
    "Kharan",
    "Aliabad",
    "Awaran",
    "Dalbandin"];
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(leading: IconButton(onPressed: (){Get.back();},icon: Icon(Icons.arrow_back,color: Colors.black,),),title: Text('Select City',style: TextStyle(color: Colors.black,fontSize: 20,fontWeight: FontWeight.bold),),backgroundColor: Colors.white,),

        body: Padding(
      padding: const EdgeInsets.only(top: 8.0,left: 20,right: 20),
      child: SearchableList<String>(
        initialList: citylist,
        builder: (dynamic user) {
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 15.0,horizontal: 10),
            child: GestureDetector(
             onTap: (){Get.to(Property('Others',search: user.toString(),));},
                child: Text(user.toString(),style:TextStyle(fontSize: 20) ,),),
          );
        },
        filter: (value) {
          return citylist.where(
                (element) {
              return element.toLowerCase().contains(value);
            },
          ).toList();
        },
        emptyWidget: const Center(child: Text('No City Found')),
        displayClearIcon: false,
        inputDecoration: InputDecoration(

            border: OutlineInputBorder(
              borderSide: const BorderSide(
                color: Colors.blue,
                width: 1.0,
              ),
              borderRadius: BorderRadius.circular(20.0),
            ),
            filled: true,
            fillColor: Colors.grey.withOpacity(0.2),
            hoverColor: Colors.grey.withOpacity(0.2),
            focusColor: Colors.grey.withOpacity(0.2),
            hintText: 'Search City',
            hintStyle: TextStyle(
                fontSize: 15,
                fontFamily: "Regular",
                color: Colors.grey)),
      ),
    ),
      ),
    );
  }
}
